"use client";

import Link from "next/link";
import { useState } from "react";

import { AuthRequired } from "@/components/auth/auth-required";
import { useAuth } from "@/components/auth/auth-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Field, Input, Textarea } from "@/components/ui/form-fields";
import { ListError, ListLoading } from "@/components/ui/feedback";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";
import { useAsyncData } from "@/hooks/use-async-data";
import type { BuildingEvent, FoundLostPost, HelpPost, Master, MasterRecommendation, ModerationContentType, ModerationRecord } from "@/types/database";

type AdminData = { foundLost: FoundLostPost[]; help: HelpPost[]; recommendations: MasterRecommendation[]; moderation: ModerationRecord[]; masters: Master[]; events: BuildingEvent[] };

export function AdminDashboard() { return <AuthRequired><AdminContent /></AuthRequired>; }
function AdminContent() {
  const { profile } = useAuth();
  if (!profile?.is_admin) return <EmptyState description="Цей розділ доступний лише адміністраторам будинку." icon="⛔" title="Немає доступу" />;
  return <AdminDataView />;
}
function AdminDataView() {
  const { profile } = useAuth(); const [message, setMessage] = useState<string | null>(null);
  const data = useAsyncData(async () => { const client = getSupabaseBrowserClient(); if (!client) throw new Error("Supabase не налаштовано."); const [foundLost, help, recommendations, moderation, masters, events] = await Promise.all([client.from("found_lost_posts").select("*").order("created_at", { ascending: false }), client.from("help_posts").select("*").order("created_at", { ascending: false }), client.from("master_recommendations").select("*").order("created_at", { ascending: false }), client.from("moderation_records").select("*"), client.from("masters").select("*").order("created_at", { ascending: false }), client.from("events").select("*").order("starts_at")]); for (const result of [foundLost, help, recommendations, moderation, masters, events]) if (result.error) throw result.error; return { foundLost: foundLost.data as FoundLostPost[], help: help.data as HelpPost[], recommendations: recommendations.data as MasterRecommendation[], moderation: moderation.data as ModerationRecord[], masters: masters.data as Master[], events: events.data as BuildingEvent[] }; });
  async function toggle(type: ModerationContentType, id: string, hidden: boolean) { if (!profile) return; const client = getSupabaseBrowserClient(); if (!client) return; const { error } = await client.from("moderation_records").upsert({ content_type: type, content_id: id, is_hidden: !hidden, moderator_id: profile.id }, { onConflict: "content_type,content_id" }); if (error) setMessage(error.message); else { setMessage(!hidden ? "Публікацію приховано." : "Публікацію повернуто." ); await data.refresh(); } }
  return <div className="space-y-5"><Card><h2 className="font-semibold">Керування основними розділами</h2><div className="mt-3 flex flex-wrap gap-2"><Link className="rounded-xl bg-[var(--tg-bg-color)] px-3 py-2 text-sm font-semibold text-[var(--tg-link-color)]" href="/announcements">Оголошення</Link><Link className="rounded-xl bg-[var(--tg-bg-color)] px-3 py-2 text-sm font-semibold text-[var(--tg-link-color)]" href="/issues">Проблеми</Link><Link className="rounded-xl bg-[var(--tg-bg-color)] px-3 py-2 text-sm font-semibold text-[var(--tg-link-color)]" href="/polls">Голосування</Link></div></Card><MasterEditor onChanged={data.refresh} /><EventEditor onChanged={data.refresh} />{message ? <p aria-live="polite" className="text-sm text-[var(--tg-link-color)]">{message}</p> : null}{data.loading ? <ListLoading /> : data.error ? <ListError message={data.error} onRetry={data.refresh} /> : <ModerationList data={data.data!} onToggle={toggle} />}</div>;
}
function MasterEditor({ onChanged }: { onChanged: () => Promise<void> }) { const { profile } = useAuth(); const [name, setName] = useState(""); const [category, setCategory] = useState(""); const [description, setDescription] = useState(""); const [contact, setContact] = useState(""); const [pending, setPending] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; setPending(true); try { const client = getSupabaseBrowserClient(); if (!client) throw new Error("Supabase не налаштовано."); const { error } = await client.from("masters").insert({ name: name.trim(), category: category.trim(), description: description.trim() || null, contact_details: contact.trim() || null, created_by: profile.id }); if (error) throw error; setName(""); setCategory(""); setDescription(""); setContact(""); await onChanged(); } finally { setPending(false); } } return <Card><h2 className="font-semibold">Додати майстра</h2><form className="mt-3 space-y-3" onSubmit={submit}><Field label="Ім’я або назва"><Input maxLength={200} onChange={(event) => setName(event.target.value)} required value={name} /></Field><Field label="Категорія"><Input maxLength={100} onChange={(event) => setCategory(event.target.value)} required value={category} /></Field><Field label="Опис"><Textarea maxLength={5000} onChange={(event) => setDescription(event.target.value)} value={description} /></Field><Field label="Контакти"><Input maxLength={500} onChange={(event) => setContact(event.target.value)} value={contact} /></Field><Button disabled={pending} type="submit">{pending ? "Зберігаємо…" : "Додати"}</Button></form></Card>; }
function EventEditor({ onChanged }: { onChanged: () => Promise<void> }) { const { profile } = useAuth(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [location, setLocation] = useState(""); const [startsAt, setStartsAt] = useState(""); const [pending, setPending] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!profile) return; setPending(true); try { const client = getSupabaseBrowserClient(); if (!client) throw new Error("Supabase не налаштовано."); const { error } = await client.from("events").insert({ title: title.trim(), description: description.trim(), location: location.trim(), starts_at: new Date(startsAt).toISOString(), organizer_id: profile.id }); if (error) throw error; setTitle(""); setDescription(""); setLocation(""); setStartsAt(""); await onChanged(); } finally { setPending(false); } } return <Card><h2 className="font-semibold">Створити подію</h2><form className="mt-3 space-y-3" onSubmit={submit}><Field label="Назва"><Input maxLength={200} onChange={(event) => setTitle(event.target.value)} required value={title} /></Field><Field label="Опис"><Textarea maxLength={5000} onChange={(event) => setDescription(event.target.value)} required value={description} /></Field><Field label="Місце"><Input maxLength={200} onChange={(event) => setLocation(event.target.value)} required value={location} /></Field><Field label="Дата і час"><Input onChange={(event) => setStartsAt(event.target.value)} required type="datetime-local" value={startsAt} /></Field><Button disabled={pending} type="submit">{pending ? "Створюємо…" : "Створити"}</Button></form></Card>; }
function ModerationList({ data, onToggle }: { data: AdminData; onToggle: (type: ModerationContentType, id: string, hidden: boolean) => Promise<void> }) { const records = new Map(data.moderation.map((record) => [`${record.content_type}:${record.content_id}`, record])); const entries: Array<{ type: ModerationContentType; id: string; title: string }> = [...data.foundLost.map((post) => ({ type: "found_lost" as const, id: post.id, title: `Знахідки: ${post.title}` })), ...data.help.map((post) => ({ type: "help_post" as const, id: post.id, title: `Допомога: ${post.title}` })), ...data.recommendations.map((recommendation) => ({ type: "master_recommendation" as const, id: recommendation.id, title: `Рекомендація: ${recommendation.rating}/5` }))]; return <Card><h2 className="font-semibold">Модерація публікацій</h2>{entries.length ? <div className="mt-3 space-y-3">{entries.map((entry) => { const hidden = records.get(`${entry.type}:${entry.id}`)?.is_hidden ?? false; return <div className="flex items-center justify-between gap-3 border-t border-black/10 pt-3" key={`${entry.type}:${entry.id}`}><p className="min-w-0 text-sm">{entry.title}</p><Button onClick={() => void onToggle(entry.type, entry.id, hidden)} variant={hidden ? "secondary" : "ghost"}>{hidden ? "Повернути" : "Приховати"}</Button></div>; })}</div> : <p className="mt-2 text-sm text-[var(--tg-hint-color)]">Немає публікацій для модерації.</p>}</Card>; }
